.circleci/config.yml
.gitignore
package-lock.json
package.json
src/app/app.component.ts
src/app/app.module.ts
src/app/chatbox/chatbox.component.html
src/app/chatbox/chatbox.component.ts
src/chat.service.spec.ts
src/chat.service.ts
src/server/index.js
src/server/package-lock.json
src/server/package.json

to run the code:
1: check out src/server and run npm install
2: checkout chitty-chat and run npm install
3. ng serve --port 3000
4. open two tap in browser to test
5. checkout src/server and run node index.js
6. wait until the terminal logs user connected x2

add socketio server and connect to client side

---

src/server/index.js

The original code was not serving the angular app. Modified so that the angular application is served to all users connecting to the server.
Test ran the server locally with `node src/server/index.js` from root directory.

Modified server code to serve angular app

---

.circleci/config.yml
Dockerfile
package-lock.json
package.json
src/server/index.js

- Created *Dockerfile* for app
- Added steps for deployment to AWS ECR/ECS
- CI
- Successfully deployed to [EC2](http://ec2-184-72-105-146.compute-1.amazonaws.com/)

Added CD using AWS ECR and ECS

---

.circleci/config.yml

- Added branch filter for deployment step such that deployment only runs after builds on master branch (as opposed to deploying after successful builds on new PRs)
- Removed aws-eks import from circleci config

Added filter requirement for deployment step

---

angular.json
src/app/app.component.ts
src/app/app.module.ts
src/app/message.service.spec.ts
src/app/message.service.ts

- Created an angular service `MessageService` that updates the database with messages for given userID, chatRoomID, etc.
- Unit tests for `MessageService`
- `ng build` and `npm start`

Added MessageService for updating messages to database

---

src/app/services/chatroom.service.ts
src/app/tests/services/auth.service.spec.ts
src/app/tests/services/chat.service.spec.ts
src/app/tests/services/chatroom.service.spec.ts
src/app/tests/services/message.service.spec.ts
src/app/tests/services/user-info.service.spec.ts

Added `getUpdates()` to `ChatroomService` to return an `Observable` of new messages added to a particular chatroom history
- `ng build` and `npm start`

Message service

---

src/app/app.component.ts
src/app/services/chatroom.service.ts
src/app/services/user-info.service.ts

added add-new-chatroom method, and modified get-chat-history method to get chat history of a chatroom only once instead of keep tracking of its changes.

Added new chatroom method

---

package-lock.json
package.json
src/app/app.component.html
src/app/chatbox/chatbox.component.html
src/app/chatbox/chatbox.component.ts
src/app/models/chat.model.ts
src/app/models/chatroom.model.ts
src/app/models/chatuser.model.ts
src/app/services/auth.service.ts

make real-time chatting working using firebase services

Data binding

---

src/app/services/chatroom.service.ts

Changed `getUpdates()` of `ChatroomService` to sort the messages by their date field before returning.
- `ng build` and `npm start`
- tested locally

Modified ChatroomService.getUpdates() to sort the messages before returning

---

src/app/tests/services/chatroom.service.spec.ts

- Added a unit test for `ChatroomService.getUpdates()`

Added A Unit Test for Chatroom Service

---

src/app/services/chatroom.service.ts
src/app/services/user-info.service.ts
src/app/tests/services/user-info.service.spec.ts

added unit test for user-info service
added some comments for chatroom service

unit test for user-info service

---

src/app/services/chatroom.service.ts
src/app/tests/services/chatroom.service.spec.ts

added unit test for chatroom service

Unit test for chatroom service

---

src/app/chatbox/chatbox.component.html
src/app/chatbox/chatbox.component.spec.ts
src/app/chatbox/chatbox.component.ts

Fixed bug in which the chatrooms panel covered up the chat messages due to the styling not updating after loading retrieving and loading the chat history content. The bug resulted from an initially empty `chatroomList`. 
Fixed a bug in which non-user messages displayed the user's displayName in their tooltip
- Removed unused code from Chatbox component
- Modified Chatbox component to dynamically retrieve the user's chatroom information
`ng build` and `npm start`

ChatboxComponent dynamically retrieves chatroom list of user

---

src/app/services/chatroom.service.ts

modified add new chatroom function, it will return a promise

modified add new chatroom function

---

src/app/chatbox/chatbox.component.spec.ts
src/app/chatbox/chatbox.component.ts

- Refactored `getChatroomList()` to call `getUserByEmail()` to avoid having to subscribe to the current user data
- Removed unused code in `ChatboxComponent`
`ng build` & `npm start`

Refactored ChatboxComponent.getChatroomList() 

---

src/app/services/chatroom.service.ts

addNewChatroom() will return the new room's id if a new room added to database sucessfully.

modified addNewChatroom function

---

src/app/services/chatroom.service.ts
src/app/tests/services/chatroom.service.spec.ts

Implemented `ChatroomService.addUserToChatroom()` to add an existing user to a chatroom
`ng build` and `npm start`

Implementation of addUserToChatroom()

---

src/app/services/auth.service.ts
src/app/tests/services/auth.service.spec.ts

unit test for auth service

---

src/app/chatbox/chatbox.component.spec.ts

Fixed unit tests in which incorrectly structured test data led to loss of test coverage of code in `getChatroomList()`.
`ng test` & `npm start`

Fixed unit tests for getChatroomList()

---

src/app/chatbox/chatbox.component.html
src/app/chatbox/chatbox.component.scss
src/app/chatbox/chatbox.component.ts

**Description**
make chat box scroll all the way to bottom whenever there is a new message comes in
make the text wrap to next line to avoid text overflow issue
**Testing**
ng test & npm start

improved UI and add auto-scroll

---

src/app/app.component.spec.ts
src/app/app.component.ts
src/app/header/header.component.spec.ts

unit test for app component

---

src/app/chatbox/chatbox.component.html
src/app/chatbox/chatbox.component.ts
src/app/createchannel/createchannel.component.html
src/app/createchannel/createchannel.component.spec.ts
src/app/createchannel/createchannel.component.ts
src/app/models/createchat.model.ts

Some edits from Shi Bin as well

Connected to firebase, fixed create channel model

---

.gitignore
.vscode/launch.json
src/app/app.component.ts
src/app/chatbox/chatbox.component.spec.ts
src/app/chatbox/chatbox.component.ts
src/app/models/user.model.ts
src/app/services/auth.service.ts
src/app/services/user-info.service.ts

**Description**
allow newly registered user to log in to our app
set 3 default chatrooms for every users
removed unused socketio code
master branch is ready to deploy for user to use
**Testing**
ng build and npm start

Register user to fire

---

src/app/chatbox/chatbox.component.html
src/app/chatbox/chatbox.component.ts

Edit: new gif of user list demonstration
This is currently what I have. Any thoughts on what I should do?
Addressed all of shibins comments.
Edit2: added unsubscribe and removed getUserByEmail stub. We'll have to figure out specifically how adding user to chatroom will work.
edit3: moved unsubscribe function inside getUserList

userlist interface 

---

package-lock.json
package.json
src/app/createchannel/createchannel.component.html
src/app/createchannel/createchannel.component.ts
src/app/services/auth.service.ts
src/app/tests/services/auth.service.spec.ts

- implemented a check for empty room names
- modified _Start Chatting!_ button so that only only valid room names close the modal
- Implemented dynamic reloading of a user's chatroom list after creating a new chatroom.
- Modified Auth service so that existing user data is not erased
- `ng build` and `npm start`
- tested locally that newly added chatrooms are reflected in the ui

Implemented dynamically loading of newly added chatroom

---

src/app/createchannel/createchannel.component.spec.ts

added unit test for create channel component
ng test

unit test for create channel component

---

Dockerfile
package.json
src/app/chatbox/chatbox.component.html
src/app/header/header.component.html
src/app/header/header.component.ts
src/app/services/tone-analyzer.service.ts
src/environments/environment.prod.ts

- Modified tone analyzer http request URI to condition on the development environment
- Refactored code to successfully run `ng build --prod`
- `ng build-prod` && `npm start`
- local build of docker image

Modified api uri depending on prod/dev environment

---

src/app/services/tone-analyzer.service.ts

Removed extra slash added to URL of http request to tone analyzer API.
`ng build` and `npm start`

Fixed http request URL to tone analyzer

---

src/app/chatbox/chatbox.component.html
src/app/chatbox/chatbox.component.scss
src/app/chatbox/chatbox.component.ts

**Description**
update emoji in chatbox according to the tone in firebase (after tone gets updated)
revison of #109 
**Testing**
ng build and npm start

update emoji according to tone in firebase

---

src/app/chatbox/chatbox.component.html
src/app/modules/material-module.ts

Was displaying a new chatroom not as a list, but as a singular input. Fixed now.

html display list was incorrect

---

src/app/services/chatroom.service.ts
src/app/services/user-info.service.ts

updated jsdoc for chatroom and userInfo service

jsdoc for chatroom and userInfo service

---

.circleci/config.yml
.gitignore
coverage/chitty-chat/index.html
karma.conf.js

- modified circleci configuration to store karma coverage files
- added minimum line coverage threshold (70%) 
`ng test`

Added minimum coverage threshold and storing of test reports on circleci

---

package-lock.json
package.json
src/app/chatbox/chatbox.component.ts
src/app/createchannel/createchannel.component.ts
src/app/models/chat.model.ts
src/app/models/chatroom.model.ts
src/app/models/chatuser.model.ts
src/app/models/createchat.model.ts
src/app/models/user.model.ts

Added preliminary js doc comments to our project. here it is after making comments
i hope I was able to explain each of the functions clearly.
I also took out the parameter of chatroomID for now in updateToneInFirebase, since it using the this.selectedChatRoomID for the current chatroom id already

added jsdoc comments to component functions for documentation coverage

---

src/app/chatbox/chatbox.component.html

avatar stays the same for each user

make avatar persistent

---

src/app/services/chatroom.service.ts
src/app/tests/services/chatroom.service.spec.ts

added delete chatroom function inside chatroom service and unit test

added delete chatroom function inside chatroom service

---

src/app/services/message.service.ts
src/app/services/tone-analyzer.service.ts
src/app/tests/services/message.service.spec.ts
src/app/tests/services/tone-analyzer.service.spec.ts
src/app/tests/services/user-info.service.spec.ts

- Added/modified unit tests for message, tone-analyze, and user-info service
- Refactored some functions for better testability
`ng test`

Added unit tests to message, tone-analyze, user-info service

---

src/app/app.component.html
src/app/app.component.ts
src/app/chatbox/chatbox.component.html
src/app/chatbox/chatbox.component.scss
src/app/chatbox/chatbox.component.ts
src/app/header/header.component.html
src/app/header/header.component.ts
src/index.html

- improve mat form field style
- add word counter and text limit
- change toggle icon
- align chatroom name with chats

Ui improvement 2

---

src/app/chatbox/chatbox.component.html
src/app/chatbox/chatbox.component.spec.ts
src/app/chatbox/chatbox.component.ts
src/app/models/chatuser.model.ts

refactored and removed unused variables of chatbox component 
- we had so many unused variables and information was being duplicated with roomnames and selectedchatroom when it was being used the same way.
added photo avatar and email tooltip to users in userlist 
added photo avatar in chat and display name as tooltip. This is dependent on the userlist of the chatroom
- this required making a function call match userid of the chat message to a userid in userlist which             
i made test functions for.
edit: after merging with hongzi's ui improvement 2

refactored chatbox component, added photo url to users and chat messages, added tooltips

---

e2e/src/app.po.ts
src/app/app.component.ts
src/app/auth.guard.ts
src/app/chatbox/chatbox.component.spec.ts
src/app/chatbox/chatbox.component.ts
src/app/createchannel/createchannel.component.ts
src/app/header/header.component.ts
src/app/login/login.component.ts
src/app/services/auth.service.ts
src/app/services/chatroom.service.ts
src/app/services/message.service.ts

https://bit.ly/chitty-ghost needed https to remove warning. we don't have a delete a single user or self from a chatroom they are from yet so this avatar shouldn't be used 
I added more comments to files to try to get all our functions covered for documentation, I may have missed some. I don't understand all the function calls that angelica's authentication service does, so i think the description can be improved.
edit:
edit after adding comments to declaration of components

added https to picture link, added more preliminary comments for functions that doesn't have jsdoc comments

---

src/app/app.module.ts
src/app/chatbox/chatbox.component.html
src/app/chatbox/chatbox.component.ts
src/app/confirmation-dialog/confirmation-dialog.component.html
src/app/confirmation-dialog/confirmation-dialog.component.spec.ts
src/app/confirmation-dialog/confirmation-dialog.component.ts
src/app/models/confirmation-dialog-data.ts

- Implemented UI for deleting chatroom
- Connected UI to service for deleting chatrooms
- Added a confirmation modal component
`ng test` and `npm start`

Added delete chatroom UI and functionality

---

src/app/app.component.ts
src/app/chatbox/chatbox.component.html
src/app/chatbox/chatbox.component.scss
src/app/chatbox/chatbox.component.spec.ts
src/app/chatbox/chatbox.component.ts
src/app/models/chatuser.model.ts
src/app/services/auth.service.ts
src/app/services/user-info.service.ts
src/app/tests/services/auth.service.spec.ts
src/app/tests/services/user-info.service.spec.ts

added user status to firebase, and modified some functions to meet the new database structure.
added a updateUser() function to update user's status in userInfoService. fixed unit test errors.

show user status (online/ offline)

---

src/app/chatbox/chatbox.component.html
src/app/chatbox/chatbox.component.scss

minor ui improvement for second release
testes with ng test and ng lint

make emoji closer to message box

---

src/app/chatbox/chatbox.component.html
src/app/chatbox/chatbox.component.scss

Reverts CSC59939/Chitty-Chat#155

Revert "make emoji closer to message box"

---

package-lock.json
package.json

Updated dependency serialize-javascript to >= 2.1.2
`ng serve`

Fix for serialize-javascript vulnerability

---

src/app/chatbox/chatbox.component.scss

make height smaller to avoid overlapping of layers

fixed create chatroom ui bug
